[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

[font]
size = 14.5

[font.normal]
family = "JetBrainsMono Nerd Font"
#family = 'Terminus'
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font"
#family = 'Terminus'
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
#family = 'Terminus'
style = "SemiBold Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
#family = 'Terminus'
style = "Bold Italic"

[window.padding]
x = 10
y = 5

[window]
decorations = "None"
opacity = 0.85
# blur = true
